

services:

  ghost:
    image: ghost
   
    ports:
      - 2368:2368
    environment:
      # see https://ghost.org/docs/config/#configuration-options
      database__client: mysql
      database__connection__host: db
      database__connection__user: root
      database__connection__password: example
      database__connection__database: ghost
      # this url value is just an example, and is likely wrong for your environment!
      url: https://your-railway-app-url # Replace with your Railway URL after deployment
      restart: always
   

  db:
    image: mysql:8.0
   
    environment:
      MYSQL_ROOT_PASSWORD: example
 